#sudo: required

language: bash

services:
  - docker

env:
  matrix:
    - BUILD_MODE=opt       DOCKER=mascucsc/archlinux-masc DOCKER_LGRAPH_SRC=/root/livehd      LGRAPH_COMPILER=g++
    - BUILD_MODE=dbg       DOCKER=mascucsc/archlinux-masc DOCKER_LGRAPH_SRC=/root/livehd      LGRAPH_COMPILER=clang++
    - BUILD_MODE=fastbuild DOCKER=mascucsc/alpine-masc    DOCKER_LGRAPH_SRC=/home/user/livehd LGRAPH_COMPILER=g++
    - BUILD_MODE=dbg       DOCKER=mascucsc/ubuntu-masc    DOCKER_LGRAPH_SRC=/root/livehd      LGRAPH_COMPILER=g++

before_install:
   - docker pull $DOCKER

script:
  - scripts/run-docker-test.sh `pwd` $BUILD_MODE $DOCKER $DOCKER_LGRAPH_SRC $LGRAPH_COMPILER

