jobs:
  - job: ArchDebug
    displayName: run coverage (archlinux, dbg, g++)

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - bash: ./scripts/run-docker-test.sh `pwd` dbg mascucsc/archlinux-masc /root/livehd g++ coverage

  - job: ArchLong
    displayName: run archlinux-masc with debug and g++ long1 tests

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - bash: ./scripts/run-docker-test.sh `pwd` dbg mascucsc/archlinux-masc /root/livehd g++ . long1

  - job: ClangLong
    displayName: run archlinux-masc with debug and clang++ long1 tests

    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - bash: ./scripts/run-docker-test.sh `pwd` dbg mascucsc/archlinux-masc /root/livehd g++ . long1


